<?php

/**
 * BaseObservation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $observer_id
 * @property integer $entity_id
 * @property Observer $Observer
 * @property Entity $Entity
 * 
 * @method integer     getObserverId()  Returns the current record's "observer_id" value
 * @method integer     getEntityId()    Returns the current record's "entity_id" value
 * @method Observer    getObserver()    Returns the current record's "Observer" value
 * @method Entity      getEntity()      Returns the current record's "Entity" value
 * @method Observation setObserverId()  Sets the current record's "observer_id" value
 * @method Observation setEntityId()    Sets the current record's "entity_id" value
 * @method Observation setObserver()    Sets the current record's "Observer" value
 * @method Observation setEntity()      Sets the current record's "Entity" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObservation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('observation');
        $this->hasColumn('observer_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('entity_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Observer', array(
             'local' => 'observer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}