<?php

/**
 * BaseDevice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $guid
 * @property Doctrine_Collection $DataSource
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getGuid()       Returns the current record's "guid" value
 * @method Doctrine_Collection getDataSource() Returns the current record's "DataSource" collection
 * @method Device              setId()         Sets the current record's "id" value
 * @method Device              setGuid()       Sets the current record's "guid" value
 * @method Device              setDataSource() Sets the current record's "DataSource" collection
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDevice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('guid', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DataSource', array(
             'refClass' => 'DataSourceRealization',
             'local' => 'device_id',
             'foreign' => 'data_source_id'));
    }
}