<?php

/**
 * BaseDoor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Locality $Locality2
 * 
 * @method Locality getLocality2() Returns the current record's "Locality2" value
 * @method Door     setLocality2() Sets the current record's "Locality2" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDoor extends Entity
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Locality as Locality2', array(
             'local' => 'locality2_id',
             'foreign' => 'id'));
    }
}