<?php

/**
 * BaseEntityType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $className
 * 
 * @method integer    getId()        Returns the current record's "id" value
 * @method string     getName()      Returns the current record's "name" value
 * @method string     getClassName() Returns the current record's "className" value
 * @method EntityType setId()        Sets the current record's "id" value
 * @method EntityType setName()      Sets the current record's "name" value
 * @method EntityType setClassName() Sets the current record's "className" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEntityType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('className', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($i18n0);
    }
}