<?php

/**
 * BaseObserver
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property User $User
 * @property Doctrine_Collection $Observants
 * @property Doctrine_Collection $Observation
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method User                getUser()        Returns the current record's "User" value
 * @method Doctrine_Collection getObservants()  Returns the current record's "Observants" collection
 * @method Doctrine_Collection getObservation() Returns the current record's "Observation" collection
 * @method Observer            setId()          Sets the current record's "id" value
 * @method Observer            setUserId()      Sets the current record's "user_id" value
 * @method Observer            setUser()        Sets the current record's "User" value
 * @method Observer            setObservants()  Sets the current record's "Observants" collection
 * @method Observer            setObservation() Sets the current record's "Observation" collection
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObserver extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('observer');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Entity as Observants', array(
             'refClass' => 'Observation',
             'local' => 'observer_id',
             'foreign' => 'entity_id'));

        $this->hasMany('Observation', array(
             'local' => 'id',
             'foreign' => 'observer_id'));
    }
}