<?php

/**
 * BaseSensor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $device_id
 * @property integer $endpoint_number
 * @property integer $cluster_id
 * @property integer $hgw_id
 * @property integer $data_source_id
 * @property Device $Device
 * @property Entity $DataSource
 * 
 * @method integer getId()              Returns the current record's "id" value
 * @method integer getDeviceId()        Returns the current record's "device_id" value
 * @method integer getEndpointNumber()  Returns the current record's "endpoint_number" value
 * @method integer getClusterId()       Returns the current record's "cluster_id" value
 * @method integer getHgwId()           Returns the current record's "hgw_id" value
 * @method integer getDataSourceId()    Returns the current record's "data_source_id" value
 * @method Device  getDevice()          Returns the current record's "Device" value
 * @method Entity  getDataSource()      Returns the current record's "DataSource" value
 * @method Sensor  setId()              Sets the current record's "id" value
 * @method Sensor  setDeviceId()        Sets the current record's "device_id" value
 * @method Sensor  setEndpointNumber()  Sets the current record's "endpoint_number" value
 * @method Sensor  setClusterId()       Sets the current record's "cluster_id" value
 * @method Sensor  setHgwId()           Sets the current record's "hgw_id" value
 * @method Sensor  setDataSourceId()    Sets the current record's "data_source_id" value
 * @method Sensor  setDevice()          Sets the current record's "Device" value
 * @method Sensor  setDataSource()      Sets the current record's "DataSource" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSensor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sensor');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('device_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('endpoint_number', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('cluster_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('hgw_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('data_source_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('guid', array(
             'type' => 'unique',
             'fields' => 
             array(
              0 => 'device_id',
              1 => 'endpoint_number',
              2 => 'cluster_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Device', array(
             'local' => 'device_id',
             'foreign' => 'id'));

        $this->hasOne('Entity as DataSource', array(
             'local' => 'data_source_id',
             'foreign' => 'id'));
    }
}