<?php

/**
 * BaseDevice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $pan_id
 * @property integer $extended_id
 * @property integer $data_source_id
 * @property Doctrine_Collection $Sensor
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getPanId()          Returns the current record's "pan_id" value
 * @method integer             getExtendedId()     Returns the current record's "extended_id" value
 * @method integer             getDataSourceId()   Returns the current record's "data_source_id" value
 * @method Doctrine_Collection getSensor()         Returns the current record's "Sensor" collection
 * @method Device              setId()             Sets the current record's "id" value
 * @method Device              setPanId()          Sets the current record's "pan_id" value
 * @method Device              setExtendedId()     Sets the current record's "extended_id" value
 * @method Device              setDataSourceId()   Sets the current record's "data_source_id" value
 * @method Device              setSensor()         Sets the current record's "Sensor" collection
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDevice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('pan_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('extended_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('data_source_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('guid', array(
             'type' => 'unique',
             'fields' => 
             array(
              0 => 'pan_id',
              1 => 'extended_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sensor', array(
             'local' => 'id',
             'foreign' => 'device_id'));
    }
}