<?php

/**
 * BaseDataSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Devices
 * 
 * @method Doctrine_Collection getDevices() Returns the current record's "Devices" collection
 * @method DataSource          setDevices() Sets the current record's "Devices" collection
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDataSource extends Entity
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Device as Devices', array(
             'refClass' => 'DataSourceRealization',
             'local' => 'data_source_id',
             'foreign' => 'device_id'));
    }
}