<?php

/**
 * BasePatient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $social_security_number
 * @property string $born_at
 * @property string $address
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getId()                     Returns the current record's "id" value
 * @method integer     getSocialSecurityNumber()   Returns the current record's "social_security_number" value
 * @method string      getBornAt()                 Returns the current record's "born_at" value
 * @method string      getAddress()                Returns the current record's "address" value
 * @method sfGuardUser getSfGuardUser()            Returns the current record's "sfGuardUser" value
 * @method Patient     setId()                     Sets the current record's "id" value
 * @method Patient     setSocialSecurityNumber()   Sets the current record's "social_security_number" value
 * @method Patient     setBornAt()                 Sets the current record's "born_at" value
 * @method Patient     setAddress()                Sets the current record's "address" value
 * @method Patient     setSfGuardUser()            Sets the current record's "sfGuardUser" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePatient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patient');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('social_security_number', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'taj szam',
             ));
        $this->hasColumn('born_at', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'szuletesi hely, idopont',
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'lakcim',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}