<?php

/**
 * BaseDataSourceAffected
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $data_source_id
 * @property integer $entity_id
 * @property Entity $DataSource
 * @property Entity $HasEffect
 * 
 * @method integer            getDataSourceId()   Returns the current record's "data_source_id" value
 * @method integer            getEntityId()       Returns the current record's "entity_id" value
 * @method Entity             getDataSource()     Returns the current record's "DataSource" value
 * @method Entity             getHasEffect()      Returns the current record's "HasEffect" value
 * @method DataSourceAffected setDataSourceId()   Sets the current record's "data_source_id" value
 * @method DataSourceAffected setEntityId()       Sets the current record's "entity_id" value
 * @method DataSourceAffected setDataSource()     Sets the current record's "DataSource" value
 * @method DataSourceAffected setHasEffect()      Sets the current record's "HasEffect" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDataSourceAffected extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('data_source_affected');
        $this->hasColumn('data_source_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('entity_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Entity as DataSource', array(
             'local' => 'data_source_id',
             'foreign' => 'id'));

        $this->hasOne('Entity as HasEffect', array(
             'local' => 'entity_id',
             'foreign' => 'id'));
    }
}