<?php

/**
 * BaseDataSourceRealization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $data_source_id
 * @property integer $device_id
 * 
 * @method integer               getDataSourceId()   Returns the current record's "data_source_id" value
 * @method integer               getDeviceId()       Returns the current record's "device_id" value
 * @method DataSourceRealization setDataSourceId()   Sets the current record's "data_source_id" value
 * @method DataSourceRealization setDeviceId()       Sets the current record's "device_id" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDataSourceRealization extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('data_source_realization');
        $this->hasColumn('data_source_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('device_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}