<?php

/**
 * BaseDevice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $guid
 * @property integer $data_source_id
 * @property Entity $DataSource
 * 
 * @method integer getId()             Returns the current record's "id" value
 * @method string  getGuid()           Returns the current record's "guid" value
 * @method integer getDataSourceId()   Returns the current record's "data_source_id" value
 * @method Entity  getDataSource()     Returns the current record's "DataSource" value
 * @method Device  setId()             Sets the current record's "id" value
 * @method Device  setGuid()           Sets the current record's "guid" value
 * @method Device  setDataSourceId()   Sets the current record's "data_source_id" value
 * @method Device  setDataSource()     Sets the current record's "DataSource" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDevice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('guid', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('data_source_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Entity as DataSource', array(
             'local' => 'data_source_id',
             'foreign' => 'id'));
    }
}