<?php

/**
 * BaseSensor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Device $Device
 * 
 * @method Device getDevice() Returns the current record's "Device" value
 * @method Sensor setDevice() Sets the current record's "Device" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSensor extends Entity
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Device', array(
             'local' => 'device_id',
             'foreign' => 'id'));
    }
}