<?php

/**
 * BasePatient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property sfGuardUser $sfGuardUser
 * 
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Patient     setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePatient extends Entity
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}