<?php

/**
 * BaseMeasurement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_id
 * @property integer $data_source_id
 * @property Entity $About
 * @property Entity $Source
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method integer     getEntityId()       Returns the current record's "entity_id" value
 * @method integer     getDataSourceId()   Returns the current record's "data_source_id" value
 * @method Entity      getAbout()          Returns the current record's "About" value
 * @method Entity      getSource()         Returns the current record's "Source" value
 * @method Measurement setId()             Sets the current record's "id" value
 * @method Measurement setEntityId()       Sets the current record's "entity_id" value
 * @method Measurement setDataSourceId()   Sets the current record's "data_source_id" value
 * @method Measurement setAbout()          Sets the current record's "About" value
 * @method Measurement setSource()         Sets the current record's "Source" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseMeasurement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('measurement');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('entity_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('data_source_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Entity as About', array(
             'local' => 'entity_id',
             'foreign' => 'id'));

        $this->hasOne('Entity as Source', array(
             'local' => 'data_source_id',
             'foreign' => 'id'));
    }
}