<?php

/**
 * BaseEntityType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $className
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Entity
 * 
 * @method string              getClassName() Returns the current record's "className" value
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getEntity()    Returns the current record's "Entity" collection
 * @method EntityType          setClassName() Sets the current record's "className" value
 * @method EntityType          setId()        Sets the current record's "id" value
 * @method EntityType          setName()      Sets the current record's "name" value
 * @method EntityType          setEntity()    Sets the current record's "Entity" collection
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntityType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_type');
        $this->hasColumn('className', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Entity', array(
             'local' => 'className',
             'foreign' => 'type'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($i18n0);
    }
}