<?php

/**
 * BaseCalendar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $ical
 * 
 * @method clob     getIcal() Returns the current record's "ical" value
 * @method Calendar setIcal() Sets the current record's "ical" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalendar extends Measurement
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('calendar');
        $this->hasColumn('ical', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}