<?php

/**
 * BaseActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property integer $start_time
 * @property integer $end_time
 * 
 * @method string   getType()       Returns the current record's "type" value
 * @method integer  getStartTime()  Returns the current record's "start_time" value
 * @method integer  getEndTime()    Returns the current record's "end_time" value
 * @method Activity setType()       Sets the current record's "type" value
 * @method Activity setStartTime()  Sets the current record's "start_time" value
 * @method Activity setEndTime()    Sets the current record's "end_time" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivity extends Measurement
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('activity');
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('start_time', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('end_time', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}