<?php

/**
 * BaseActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activity_type_id
 * @property integer $start_time
 * @property integer $end_time
 * @property ActivityType $ActivityType
 * 
 * @method integer      getActivityTypeId()   Returns the current record's "activity_type_id" value
 * @method integer      getStartTime()        Returns the current record's "start_time" value
 * @method integer      getEndTime()          Returns the current record's "end_time" value
 * @method ActivityType getActivityType()     Returns the current record's "ActivityType" value
 * @method Activity     setActivityTypeId()   Sets the current record's "activity_type_id" value
 * @method Activity     setStartTime()        Sets the current record's "start_time" value
 * @method Activity     setEndTime()          Sets the current record's "end_time" value
 * @method Activity     setActivityType()     Sets the current record's "ActivityType" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivity extends Measurement
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('activity');
        $this->hasColumn('activity_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('start_time', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('end_time', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ActivityType', array(
             'local' => 'activity_type_id',
             'foreign' => 'id'));
    }
}