<?php

/**
 * BaseActivityType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property Doctrine_Collection $Activities
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getType()       Returns the current record's "type" value
 * @method Doctrine_Collection getActivities() Returns the current record's "Activities" collection
 * @method ActivityType        setId()         Sets the current record's "id" value
 * @method ActivityType        setType()       Sets the current record's "type" value
 * @method ActivityType        setActivities() Sets the current record's "Activities" collection
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Activity as Activities', array(
             'local' => 'id',
             'foreign' => 'activity_type_id'));
    }
}