# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:
  sf_admin_dash:
    site:                         CCE-web
    include_jquery:               false
    categories:
      Users:
        items:
          Patients:
            url:    patient
          Observers:
            url:    observer
      Config:
        items:
          Entity tree editor:
            url:    entity
          Locality types:
            url:    locality_type
          Devices:
            url:    device
      Measurements:
        items:
          Activity:
            url:    activity
          Ekg:
            url:    ekg
          Battery:
            url:    battery
          Humidity:
            url:    humidity
          Light:
            url:    light
          Motion:
            url:    motion
          OnOff:
            url:    onOff
          OpenClosed:
            url:    openClosed
          Temperature:
            url:    temperature
          Activation:
            url:    activation
            