# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            bd1f5123ce5e15f120f90f603f9610d202e8bbac

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure

    standard_helpers:
      - Partial
      - sfAssetsManager

    enabled_modules:
      - sfAdminDash
      - sfGuardAuth
      - sfJqueryTreeDoctrineManager
      #Measurement plugin backend modules
      - activityBackend
      - activity_type
      - ekgBackend
      - batteryBackend
      - humidityBackend
      - lightBackend
      - motionBackend
      - onOffBackend
      - openClosedBackend
      - temperatureBackend
      - activationBackend
      - cupboardBackend
      - electricStoveBackend
      - fridgeBackend
      - wardrobeBackend
      - bedBackend
      - powerBackend
      - forceCellBackend
      - default
      
  .actions:
    error_404_module:       default
    error_404_action:       error404
    
