<?php

/**
 * PluginCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCalendarTable extends MeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCalendar');
    }
}