<?php

/**
 * PluginActivityTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginActivityTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginActivityTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginActivityType');
    }
}