<?php

/**
 * PluginActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginActivityTable extends MeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginActivity');
    }
}