<?php

/**
 * ActivationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivationTable extends PluginActivationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Activation');
    }
}