<?php

/**
 * BatteryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BatteryTable extends PluginBatteryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object BatteryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Battery');
    }
}