<?php

/**
 * ForceCellTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForceCellTable extends PluginForceCellTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForceCellTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForceCell');
    }
}