<?php

/**
 * HumidityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HumidityTable extends PluginHumidityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HumidityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Humidity');
    }
}