<?php

/**
 * LightTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LightTable extends PluginLightTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LightTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Light');
    }
}