<?php

/**
 * MotionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MotionTable extends PluginMotionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MotionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Motion');
    }
}