<?php

/**
 * OnOffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OnOffTable extends PluginOnOffTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OnOffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OnOff');
    }
}