<?php

/**
 * OpenClosedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpenClosedTable extends PluginOpenClosedTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpenClosedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpenClosed');
    }
}