<?php

/**
 * TemperatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TemperatureTable extends PluginTemperatureTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TemperatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Temperature');
    }
}