<?php

/**
 * UsageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsageTable extends PluginUsageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usage');
    }
}