<?php

/**
 * DataSourceAffectedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DataSourceAffectedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DataSourceAffectedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DataSourceAffected');
    }
}