<?php

/**
 * DataSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DataSourceTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return DataSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DataSource');
    }
}