<?php

/**
 * DataSourceRealizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DataSourceRealizationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DataSourceRealizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DataSourceRealization');
    }
}