<?php

/**
 * DoorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoorTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return DoorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Door');
    }
}