<?php

/**
 * EmptyTimedMeasurementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmptyTimedMeasurementTable extends TimedMeasurementTable
{

  /**
   * Returns an instance of this class.
   *
   * @return EmptyTimedMeasurementTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('EmptyTimedMeasurement');
  }

  public function getMeasurementsAbout(Entity $entity, TimePeriod $period)
  {
    $measurements = $this->createQuery('m')
                    ->select('m.timestamp')
                    ->andWhere('m.entity_id = ?', $entity->id)
                    ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                    ->andWhere('m.timestamp BETWEEN ? AND ?', array($period->from, $period->to))
                    ->execute();
    foreach ($measurements as &$measurement)
    {
      unset($measurement['id']);
      $measurement['timestamp'] = (int) $measurement['timestamp'];
    }
    return $measurements;
  }

}