<?php

/**
 * Entity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Entity extends BaseEntity
{

  public function __toString()
  {
    return "{$this->name} ({$this->type} {$this->id})";
  }

  /**
   * getter for node associated with this record
   *
   * @return Doctrine_Node_NestedSet
   */
  public function getNode()
  {
    return parent::getNode();
  }

  public function getActiveChannels()
  {
    /* 
     * TODO ez trükkös
     * Lehet minden csatornára külön lekérdezni, hogy van-e releváns adat,
     * de ez elég lassú és kell hozzá az összes regisztrált csatorna listája.
     * Valószínű viszont, hogy valahol úgy is szükség lesz erre a listára, így
     * mindenképpen össze kell állítani.
     * 
     * Lehetne egy plusz táblát is csinálni, amiben a különböző entitásokon
     * akív csatornákat kezelhetnénk. Ez lehetne normatív, vagyis csak azokat
     * az adatok fogadjuk be, ami itt engedélyezve van, vagy leíró, azaz
     * a bejövő adatok szerint frissítjük. - ez egyfajta cache így
     */
  }

}
