<?php

/**
 * EntityTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntityTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntityTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EntityType');
    }
}