<?php

/**
 * Home
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Home extends BaseHome
{

  public function getDataSources()
  {
    $q = DataSourceTable::getInstance()->createQuery('dataSource');
    $tree = DataSourceTable::getInstance()->getTree(); /* @var $tree Doctrine_Tree_NestedSet */
    $tree->setBaseQuery($q);
    $ret = $tree->fetchTree(array('root_id' => $this->getNode()->getRootValue()));
    $tree->resetBaseQuery();
    return $ret;
  }

  public function getLocalities()
  {
    $q = LocalityTable::getInstance()->createQuery('locality');
    $tree = LocalityTable::getInstance()->getTree(); /* @var $tree Doctrine_Tree_NestedSet */
    $tree->setBaseQuery($q);
    $ret = $tree->fetchTree(array('root_id' => $this->getNode()->getRootValue()));
    $tree->resetBaseQuery();
    return $ret;
  }

}
