<?php

/**
 * LocalityTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocalityTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return LocalityTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LocalityType');
    }
}