<?php

/**
 * LocalityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocalityTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return LocalityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Locality');
    }
}