<?php

/**
 * MeasurementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MeasurementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MeasurementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Measurement');
    }
}