<?php

/**
 * MeasurementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MeasurementTable extends Doctrine_Table
{

  /**
   *
   * @abstract
   * @param Entity $entity
   * @param TimePeriod $period
   */
  public function getMeasurementsAbout(Entity $entity, TimePeriod $period)
  {

  }

  public function getChannels()
  {
    return array(
        'Activity',
        'Ekg',
        'Battery',
        'Humidity',
        'Light',
        'Motion',
        'OnOff',
        'OpenClosed',
        'Temperature',
        'Activation',
        'Calendar',
        'Power',
    );
  }

  /**
   * Returns an instance of this class.
   *
   * @return MeasurementTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Measurement');
  }

}