<?php

/**
 * MeasurementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MeasurementTable extends Doctrine_Table
{

  public function getChannels()
  {
    return array(
        'Activity',
        'Ekg',
        'Battery',
        'Humidity',
        'Light',
        'Motion',
        'OnOff',
        'OpenClose',
        'Temperature',
        'Activation',
    );
  }

  /**
   * Returns an instance of this class.
   *
   * @return MeasurementTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Measurement');
  }

}