<?php

/**
 * Measurement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Measurement extends BaseMeasurement
{

  static public function create(DataSource $dataSource, $data)
  {
    $m = new static();
    $m->Source = $dataSource;
    $m->loadAbout($data);
    $m->loadData($data);
    return $m;
  }

  protected function loadAbout($data)
  {
    $this->About = $this->Source->getNode()->getParent();
  }

  protected function loadData($data)
  {
    
  }
  

}
