<?php

/**
 * Observer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Observer extends BaseObserver
{

  public function getUsername()
  {
    return $this->sfGuardUser->username;
  }

}
