<?php

/**
 * ObservationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObservationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ObservationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Observation');
    }
}