<?php

/**
 * ObserverTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObserverTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObserverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Observer');
    }
}