<?php

/**
 * Patient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Patient extends BasePatient
{

  public function getHome()
  {
    return $this->getNode()->getParent();
  }

  public function getName()
  {
    return $this->sfGuardUser->getName();
  }

  public function postSave($event)
  {
    parent::postSave($event);
    $calendar = CalendarTable::getByEntity($this);
    if($this->calendar_url && !$calendar) {
      $calendar = new Calendar();
      $calendar->About = $this;
      $calendar->Source = $this;
      $calendar->save();
    } elseif (!$this->calendar_url && $calendar) {
      $calendar->delete();
    }
  }

}
