<?php

/**
 * ScalarTimedMeasurementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScalarTimedMeasurementTable extends TimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return ScalarTimedMeasurementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScalarTimedMeasurement');
    }
}