<?php

/**
 * SensorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SensorTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SensorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sensor');
    }
}