<?php

/**
 * WindowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WindowTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WindowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Window');
    }
}