generator:
  class: sfDoctrineGenerator
  param:
    model_class:           patient
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          patient
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, comment, social_security_number, born_at, address ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
