packages: 
  layout:
    css: frontend/layout.css
  entity_indexRecursive:
    import:
      - jquery
      - jquery.urlTemplate
      - jquery.mousewheel
      - highcharts
      - jquery.ui.draggable
      - wdCalendar
    css: entity/indexRecursive.css
