# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:    /
  param:  { module: entity, action: index }

datasource:
  url:      /datasource/:id
  class:    sfDoctrineRoute
  options:  { model: DataSource, type: object }
  param:    { module: dataSource, action: createMeasurement }
  requirements:
    entityId:         \d+
    sf_method:        post

config:
  url:      /Home/:id/config/:action.:sf_format
  class:    sfDoctrineRoute
  options:  { model: Home, type: object }
  param:    { module: config }
  requirements:
    id:               \d+

javascript:
  url:    /assets/dynamic/entity/indexRecursive.js
  param:  { module: entity, action: javascript, sf_format: js }

calendar_refresh:
  url:      /:type/:id/Calendar/refresh
  class:    sfDoctrineRoute
  options:  { model: Entity, type: object }
  param:    { module: entity, action: calendarRefresh }
  requirements:
    type:       \S+
    id:         \d+
    sf_method:  [post]

measurement_data:
  url:      /:type/:id/:channelName
  class:    sfDoctrineRoute
  options:  { model: Entity, type: object }
  param:    { module: entity, action: data }
  requirements:
    type:       \S+
    id:         \d+
    channelName:    \S+
    from:       \d+
    to:         \d+

calendar_data:
  url:      /:type/:id/Calendar
  class:    sfDoctrineRoute
  options:  { model: Entity, type: object }
  param:    { module: entity, action: calendarData }
  requirements:
    type:       \S+
    id:         \d+
    showdate:   \S+
    timezone:   \d+
    viewtype:   \S+
    sf_method:  [get, post]

entity_index:
  url:      /:type/:id
  class:    sfDoctrineRoute
  options:  { model: Entity, type: object }
  param:    { module: entity, action: indexRecursive }
  requirements:
    type:       \S+
    id:         \d+
