# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:    /
  param:  { module: entity, action: index }

datasource:
  url:      /datasource/:id/:channel
  class:    sfDoctrineRoute
  options:  { model: DataSource, type: object }
  param:    { module: dataSource, action: createMeasurement }
  requirements:
    entityId:         \d+
    channel:          \S+
    sf_method:        post

javascript:
  url:    /assets/dynamic/entity/indexRecursive.js
  param:  { module: entity, action: javascript, sf_format: js }

measurement_data:
  url:      /:type/:id/:channel
  class:    sfDoctrineRoute
  options:  { model: Entity, type: object }
  param:    { module: entity, action: data }
  requirements:
    type:       \S+
    id:         \d+
    channel:    \S+
    from:       \d+
    to:         \d+

entity_index:
  url:      /:type/:id
  class:    sfDoctrineRoute
  options:  { model: Entity, type: object }
  param:    { module: entity, action: indexRecursive }
  requirements:
    type:       \S+
    id:         \d+
