# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:    /
  param:  { module: patient, action: index }

datasource:
  url:      /datasource/:id/:channel
  class:    sfDoctrineRoute
  options:  { model: DataSource, type: object }
  param:    { module: dataSource, action: createMeasurement }
  requirements:
    entityId:         \d+
    channel:          \S+
    sf_method:        post

entity_index:
  url:   /:type/:id
  class:    sfDoctrineRoute
  options:  { model: Entity, type: object }
  param:    { module: entity, action: index }
  requirements:
    entityType:       \S+
    entityId:         \d+


#default:
#  url:   /:entityType/:entityId/*
