<?php

/**
 * PluginForceCellTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginForceCellTable extends ScalarTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginForceCellTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginForceCell');
    }
}