<?php

/**
 * PluginLightTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLightTable extends ScalarTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLightTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLight');
    }
}