<?php

/**
 * PluginOnOffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOnOffTable extends ScalarTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOnOffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOnOff');
    }
}