<?php

/**
 * PluginBatteryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBatteryTable extends ScalarTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBatteryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBattery');
    }
}