<?php

/**
 * PluginOpenClosedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOpenClosedTable extends ScalarTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOpenClosedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOpenClosed');
    }
}