<?php

/**
 * PluginActivationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginActivationTable extends EmptyTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginActivationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginActivation');
    }
}