<?php

/**
 * PluginOpenClosedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOpenClosedTable extends ScalarTimedMeasurementTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object PluginOpenClosedTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginOpenClosed');
  }

  public function getMeasurementsAbout(Entity $entity, TimePeriod $period)
  {
    $measurements = parent::getMeasurementsAbout($entity, $period)
                    ->andWhere('m.timestamp BETWEEN ? AND ?', array($period->from, $period->to))
                    ->execute();
    foreach ($measurements as &$measurement)
    {
      unset ($measurement['id']);
      $measurement['timestamp'] = (int)$measurement['timestamp'];
    }
    return $measurements;
  }

}
