<?php

/**
 * PluginOpenCloseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOpenCloseTable extends ScalarTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOpenCloseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOpenClose');
    }
}