<?php

/**
 * PluginBattery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginBattery extends BaseBattery{
    protected function loadData($data){
        $this -> level = $data['data']; // a korabbiak szerint, pl: data:"normal"
        $this -> timestamp = $data['timestamp'];
        
        $mailer = sfContext::getInstance()->getMailer();
        
        $message = $mailer -> compose(
            array('emt.bme.hu' => 'emt'),
            "mihaly.gabor.dev@gmail.com",
            'hello',
            <<<EOF
A tapfeszultseg a kritikus szintre esett a(z) {$data["id"]} azonositoju eszkozon.
EOF
        );
        
        // NO echo("getInstance ".property_exists($this, 'getInstance'));
        echo("self::getNode ".property_exists(self, 'getNode'));
        //echo(var_dump(
        //$node = self::getNode();//);
        //echo(self :: getNode());
        //$mailer -> send($message);
    }
}
