<?php

/**
 * PluginUsageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUsageTable extends EmptyTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUsageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUsage');
    }
}