<?php

/**
 * PluginTemperatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTemperatureTable extends ScalarTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTemperatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTemperature');
    }
}