<?php

/**
 * PluginPowerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPowerTable extends ScalarTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPowerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPower');
    }
}