<?php

/**
 * PluginLight
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginLight extends BaseLight{
    protected function loadData($data){
        echo "let there be light!";

        $this->value = $data['data'];
        $this->timestamp = $data['timestamp'];
    }

}
