<?php

/**
 * PluginMotionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMotionTable extends EmptyTimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMotionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMotion');
    }
}