<?php

/**
 * PluginOpenClosed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginOpenClosed extends BaseOpenClosed{
    protected function loadData($data){
        //var_dump($data);
        $this->value = $data['data'];
        $this->timestamp = $data['timestamp'];
    }
}
