<?php

/**
 * BaseBattery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $level
 * 
 * @method enum    getLevel() Returns the current record's "level" value
 * @method Battery setLevel() Sets the current record's "level" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBattery extends ScalarTimedMeasurement
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('battery');
        $this->hasColumn('level', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'low',
              1 => 'normal',
             ),
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}