<?php

/**
 * BaseOpenClosed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $value
 * 
 * @method enum       getValue() Returns the current record's "value" value
 * @method OpenClosed setValue() Sets the current record's "value" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOpenClosed extends ScalarTimedMeasurement
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('open_closed');
        $this->hasColumn('value', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'open',
              1 => 'closed',
             ),
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}