<?php

/**
 * BaseTemperature
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property float $value
 * 
 * @method float       getValue() Returns the current record's "value" value
 * @method Temperature setValue() Sets the current record's "value" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTemperature extends ScalarTimedMeasurement
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('temperature');
        $this->hasColumn('value', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}