<?php

/**
 * BaseMotion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $value
 * 
 * @method boolean getValue() Returns the current record's "value" value
 * @method Motion  setValue() Sets the current record's "value" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMotion extends ScalarTimedMeasurement
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('motion');
        $this->hasColumn('value', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}