<?php

/**
 * BaseHumidity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseHumidity extends ScalarTimedMeasurement
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('humidity');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}