generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Entity
    theme:                 nestedSet
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          entity
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  ~
      list:
        display:  [ type, comment ]
        sort:     [ lft, asc ]
        max_per_page: 1000
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
