<?php

/**
 * PluginEKGTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEKGTable extends TimedMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEKGTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEKG');
    }
}