generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EntityType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          entity_type
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: {}
        object_actions:
          _edit: ~
        actions: {}
      filter:  ~
      form:    ~
      edit:
        title: Edit entity type %%className%%
      new:     ~
