<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addentity extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('entity', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'comment' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'type' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'locality_type_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'locality_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'locality2_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'remark' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'root_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'lft' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'rgt' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'level' => 
             array(
              'type' => 'integer',
              'length' => 2,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('entity');
    }
}