<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('activity', 'activity_entity_id_entity_id', array(
             'name' => 'activity_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('activity', 'activity_data_source_id_entity_id', array(
             'name' => 'activity_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('entity', 'entity_locality_id_entity_id', array(
             'name' => 'entity_locality_id_entity_id',
             'local' => 'locality_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('data_source_realization', 'data_source_realization_data_source_id_entity_id', array(
             'name' => 'data_source_realization_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('e_k_g', 'e_k_g_entity_id_entity_id', array(
             'name' => 'e_k_g_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('e_k_g', 'e_k_g_data_source_id_entity_id', array(
             'name' => 'e_k_g_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('measurement', 'measurement_entity_id_entity_id', array(
             'name' => 'measurement_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('measurement', 'measurement_data_source_id_entity_id', array(
             'name' => 'measurement_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('observation', 'observation_observer_id_observer_id', array(
             'name' => 'observation_observer_id_observer_id',
             'local' => 'observer_id',
             'foreign' => 'id',
             'foreignTable' => 'observer',
             ));
        $this->createForeignKey('observation', 'observation_entity_id_entity_id', array(
             'name' => 'observation_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('observer', 'observer_user_id_user_id', array(
             'name' => 'observer_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('patient', 'patient_user_id_user_id', array(
             'name' => 'patient_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('activity', 'activity_entity_id_entity_id');
        $this->dropForeignKey('activity', 'activity_data_source_id_entity_id');
        $this->dropForeignKey('entity', 'entity_locality_id_entity_id');
        $this->dropForeignKey('data_source_realization', 'data_source_realization_data_source_id_entity_id');
        $this->dropForeignKey('e_k_g', 'e_k_g_entity_id_entity_id');
        $this->dropForeignKey('e_k_g', 'e_k_g_data_source_id_entity_id');
        $this->dropForeignKey('measurement', 'measurement_entity_id_entity_id');
        $this->dropForeignKey('measurement', 'measurement_data_source_id_entity_id');
        $this->dropForeignKey('observation', 'observation_observer_id_observer_id');
        $this->dropForeignKey('observation', 'observation_entity_id_entity_id');
        $this->dropForeignKey('observer', 'observer_user_id_user_id');
        $this->dropForeignKey('patient', 'patient_user_id_user_id');
    }
}