<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addobservation extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('observation', array(
             'observer_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'entity_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'observer_id',
              1 => 'entity_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('observation');
    }
}