<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpatient extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('patient', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'social_security_number' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'comment' => 'taj szam',
              'length' => 4,
             ),
             'born_at' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'comment' => 'szuletesi hely, idopont',
              'length' => 255,
             ),
             'address' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'comment' => 'lakcim',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('patient');
    }
}