<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adduser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'username' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 128,
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 128,
             ),
             'salt' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'is_super_admin' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'last_login' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
              'name_idx' => 
              array(
              'fields' => 
              array(
               0 => 'username',
              ),
              'unique' => true,
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user');
    }
}