<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addekg extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('e_k_g', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'entity_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'data_source_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'timestamp' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'started_by' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 10,
             ),
             'heart_rate' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 2,
             ),
             'st_segment_elevation_ch1' => 
             array(
              'type' => 'float',
              'notnull' => true,
              'comment' => 'in volts',
              'length' => 10,
              'scale' => '6',
             ),
             'st_segment_elevation_ch2' => 
             array(
              'type' => 'float',
              'notnull' => true,
              'comment' => 'in volts',
              'length' => 10,
              'scale' => '6',
             ),
             'commonparams' => 
             array(
              'type' => 'array',
              'notnull' => true,
              'length' => NULL,
             ),
             'channelparams' => 
             array(
              'type' => 'array',
              'notnull' => true,
              'length' => NULL,
             ),
             'averages' => 
             array(
              'type' => 'array',
              'notnull' => true,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
              'timestamp' => 
              array(
              'fields' => 
              array(
               0 => 'timestamp',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('e_k_g');
    }
}