<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adduseractivationcode extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user_activation_code', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'user_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user_activation_code');
    }
}