<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddatasourcerealization extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('data_source_realization', array(
             'data_source_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'device_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'data_source_id',
              1 => 'device_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('data_source_realization');
    }
}