<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('activity', 'activity_entity_id_entity_id', array(
             'name' => 'activity_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('activity', 'activity_data_source_id_entity_id', array(
             'name' => 'activity_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('data_source_realization', 'data_source_realization_data_source_id_entity_id', array(
             'name' => 'data_source_realization_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('data_source_realization', 'data_source_realization_device_id_device_id', array(
             'name' => 'data_source_realization_device_id_device_id',
             'local' => 'device_id',
             'foreign' => 'id',
             'foreignTable' => 'device',
             ));
        $this->createForeignKey('entity', 'entity_locality2_id_entity_id', array(
             'name' => 'entity_locality2_id_entity_id',
             'local' => 'locality2_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('entity', 'entity_locality_type_id_locality_type_id', array(
             'name' => 'entity_locality_type_id_locality_type_id',
             'local' => 'locality_type_id',
             'foreign' => 'id',
             'foreignTable' => 'locality_type',
             ));
        $this->createForeignKey('entity', 'entity_locality_id_entity_id', array(
             'name' => 'entity_locality_id_entity_id',
             'local' => 'locality_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('e_k_g', 'e_k_g_entity_id_entity_id', array(
             'name' => 'e_k_g_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('e_k_g', 'e_k_g_data_source_id_entity_id', array(
             'name' => 'e_k_g_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('measurement', 'measurement_entity_id_entity_id', array(
             'name' => 'measurement_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('measurement', 'measurement_data_source_id_entity_id', array(
             'name' => 'measurement_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('observation', 'observation_observer_id_observer_id', array(
             'name' => 'observation_observer_id_observer_id',
             'local' => 'observer_id',
             'foreign' => 'id',
             'foreignTable' => 'observer',
             ));
        $this->createForeignKey('observation', 'observation_entity_id_entity_id', array(
             'name' => 'observation_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('observer', 'observer_user_id_sf_guard_user_id', array(
             'name' => 'observer_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('patient', 'patient_user_id_sf_guard_user_id', array(
             'name' => 'patient_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_forgot_password_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_group_permission_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_group_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_remember_key_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_group_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_user_group_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_permission_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_user_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('activity', 'activity_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('activity', 'activity_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('data_source_realization', 'data_source_realization_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('data_source_realization', 'data_source_realization_device_id', array(
             'fields' => 
             array(
              0 => 'device_id',
             ),
             ));
        $this->addIndex('entity', 'entity_locality2_id', array(
             'fields' => 
             array(
              0 => 'locality2_id',
             ),
             ));
        $this->addIndex('entity', 'entity_type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
        $this->addIndex('entity', 'entity_locality_type_id', array(
             'fields' => 
             array(
              0 => 'locality_type_id',
             ),
             ));
        $this->addIndex('entity', 'entity_locality_id', array(
             'fields' => 
             array(
              0 => 'locality_id',
             ),
             ));
        $this->addIndex('e_k_g', 'e_k_g_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('e_k_g', 'e_k_g_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('measurement', 'measurement_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('measurement', 'measurement_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('observation', 'observation_observer_id', array(
             'fields' => 
             array(
              0 => 'observer_id',
             ),
             ));
        $this->addIndex('observation', 'observation_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('observer', 'observer_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('patient', 'patient_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_group_permission', 'sf_guard_group_permission_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->addIndex('sf_guard_group_permission', 'sf_guard_group_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->addIndex('sf_guard_remember_key', 'sf_guard_remember_key_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_user_group', 'sf_guard_user_group_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_user_group', 'sf_guard_user_group_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->addIndex('sf_guard_user_permission', 'sf_guard_user_permission_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_user_permission', 'sf_guard_user_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('activity', 'activity_entity_id_entity_id');
        $this->dropForeignKey('activity', 'activity_data_source_id_entity_id');
        $this->dropForeignKey('data_source_realization', 'data_source_realization_data_source_id_entity_id');
        $this->dropForeignKey('data_source_realization', 'data_source_realization_device_id_device_id');
        $this->dropForeignKey('entity', 'entity_locality2_id_entity_id');
        $this->dropForeignKey('entity', 'entity_locality_type_id_locality_type_id');
        $this->dropForeignKey('entity', 'entity_locality_id_entity_id');
        $this->dropForeignKey('e_k_g', 'e_k_g_entity_id_entity_id');
        $this->dropForeignKey('e_k_g', 'e_k_g_data_source_id_entity_id');
        $this->dropForeignKey('measurement', 'measurement_entity_id_entity_id');
        $this->dropForeignKey('measurement', 'measurement_data_source_id_entity_id');
        $this->dropForeignKey('observation', 'observation_observer_id_observer_id');
        $this->dropForeignKey('observation', 'observation_entity_id_entity_id');
        $this->dropForeignKey('observer', 'observer_user_id_sf_guard_user_id');
        $this->dropForeignKey('patient', 'patient_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id');
        $this->dropForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id');
        $this->removeIndex('activity', 'activity_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('activity', 'activity_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('data_source_realization', 'data_source_realization_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('data_source_realization', 'data_source_realization_device_id', array(
             'fields' => 
             array(
              0 => 'device_id',
             ),
             ));
        $this->removeIndex('entity', 'entity_locality2_id', array(
             'fields' => 
             array(
              0 => 'locality2_id',
             ),
             ));
        $this->removeIndex('entity', 'entity_type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
        $this->removeIndex('entity', 'entity_locality_type_id', array(
             'fields' => 
             array(
              0 => 'locality_type_id',
             ),
             ));
        $this->removeIndex('entity', 'entity_locality_id', array(
             'fields' => 
             array(
              0 => 'locality_id',
             ),
             ));
        $this->removeIndex('e_k_g', 'e_k_g_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('e_k_g', 'e_k_g_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('measurement', 'measurement_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('measurement', 'measurement_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('observation', 'observation_observer_id', array(
             'fields' => 
             array(
              0 => 'observer_id',
             ),
             ));
        $this->removeIndex('observation', 'observation_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('observer', 'observer_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('patient', 'patient_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_group_permission', 'sf_guard_group_permission_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->removeIndex('sf_guard_group_permission', 'sf_guard_group_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->removeIndex('sf_guard_remember_key', 'sf_guard_remember_key_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_group', 'sf_guard_user_group_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_group', 'sf_guard_user_group_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_permission', 'sf_guard_user_permission_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_permission', 'sf_guard_user_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
    }
}