<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('activation', 'activation_entity_id_entity_id', array(
             'name' => 'activation_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('activation', 'activation_data_source_id_entity_id', array(
             'name' => 'activation_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('battery', 'battery_entity_id_entity_id', array(
             'name' => 'battery_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('battery', 'battery_data_source_id_entity_id', array(
             'name' => 'battery_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('humidity', 'humidity_entity_id_entity_id', array(
             'name' => 'humidity_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('humidity', 'humidity_data_source_id_entity_id', array(
             'name' => 'humidity_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('light', 'light_entity_id_entity_id', array(
             'name' => 'light_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('light', 'light_data_source_id_entity_id', array(
             'name' => 'light_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('motion', 'motion_entity_id_entity_id', array(
             'name' => 'motion_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('motion', 'motion_data_source_id_entity_id', array(
             'name' => 'motion_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('on_off', 'on_off_entity_id_entity_id', array(
             'name' => 'on_off_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('on_off', 'on_off_data_source_id_entity_id', array(
             'name' => 'on_off_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('open_close', 'open_close_entity_id_entity_id', array(
             'name' => 'open_close_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('open_close', 'open_close_data_source_id_entity_id', array(
             'name' => 'open_close_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('temperature', 'temperature_entity_id_entity_id', array(
             'name' => 'temperature_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('temperature', 'temperature_data_source_id_entity_id', array(
             'name' => 'temperature_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->addIndex('activation', 'activation_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('activation', 'activation_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('battery', 'battery_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('battery', 'battery_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('humidity', 'humidity_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('humidity', 'humidity_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('light', 'light_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('light', 'light_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('motion', 'motion_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('motion', 'motion_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('on_off', 'on_off_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('on_off', 'on_off_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('open_close', 'open_close_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('open_close', 'open_close_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('temperature', 'temperature_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('temperature', 'temperature_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('activation', 'activation_entity_id_entity_id');
        $this->dropForeignKey('activation', 'activation_data_source_id_entity_id');
        $this->dropForeignKey('battery', 'battery_entity_id_entity_id');
        $this->dropForeignKey('battery', 'battery_data_source_id_entity_id');
        $this->dropForeignKey('humidity', 'humidity_entity_id_entity_id');
        $this->dropForeignKey('humidity', 'humidity_data_source_id_entity_id');
        $this->dropForeignKey('light', 'light_entity_id_entity_id');
        $this->dropForeignKey('light', 'light_data_source_id_entity_id');
        $this->dropForeignKey('motion', 'motion_entity_id_entity_id');
        $this->dropForeignKey('motion', 'motion_data_source_id_entity_id');
        $this->dropForeignKey('on_off', 'on_off_entity_id_entity_id');
        $this->dropForeignKey('on_off', 'on_off_data_source_id_entity_id');
        $this->dropForeignKey('open_close', 'open_close_entity_id_entity_id');
        $this->dropForeignKey('open_close', 'open_close_data_source_id_entity_id');
        $this->dropForeignKey('temperature', 'temperature_entity_id_entity_id');
        $this->dropForeignKey('temperature', 'temperature_data_source_id_entity_id');
        $this->removeIndex('activation', 'activation_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('activation', 'activation_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('battery', 'battery_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('battery', 'battery_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('humidity', 'humidity_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('humidity', 'humidity_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('light', 'light_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('light', 'light_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('motion', 'motion_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('motion', 'motion_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('on_off', 'on_off_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('on_off', 'on_off_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('open_close', 'open_close_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('open_close', 'open_close_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('temperature', 'temperature_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('temperature', 'temperature_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
    }
}