<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('open_closed', 'open_closed_entity_id_entity_id', array(
             'name' => 'open_closed_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('open_closed', 'open_closed_data_source_id_entity_id', array(
             'name' => 'open_closed_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->addIndex('open_closed', 'open_closed_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('open_closed', 'open_closed_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('open_closed', 'open_closed_entity_id_entity_id');
        $this->dropForeignKey('open_closed', 'open_closed_data_source_id_entity_id');
        $this->removeIndex('open_closed', 'open_closed_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('open_closed', 'open_closed_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
    }
}