<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('motion', 'value', 'boolean', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('open_closed', 'value', 'enum', '', array(
             'values' => 
             array(
              0 => 'open',
              1 => 'closed',
             ),
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('motion', 'value');
    }
}