<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('entity', 'entity_locality_type_id_locality_type_id', array(
             'name' => 'entity_locality_type_id_locality_type_id',
             'local' => 'locality_type_id',
             'foreign' => 'id',
             'foreignTable' => 'locality_type',
             ));
        $this->createForeignKey('entity', 'entity_locality_id_entity_id', array(
             'name' => 'entity_locality_id_entity_id',
             'local' => 'locality_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('entity', 'entity_locality2_id_entity_id', array(
             'name' => 'entity_locality2_id_entity_id',
             'local' => 'locality2_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->addIndex('entity', 'entity_locality_type_id', array(
             'fields' => 
             array(
              0 => 'locality_type_id',
             ),
             ));
        $this->addIndex('entity', 'entity_locality_id', array(
             'fields' => 
             array(
              0 => 'locality_id',
             ),
             ));
        $this->addIndex('entity', 'entity_locality2_id', array(
             'fields' => 
             array(
              0 => 'locality2_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('entity', 'entity_locality_type_id_locality_type_id');
        $this->dropForeignKey('entity', 'entity_locality_id_entity_id');
        $this->dropForeignKey('entity', 'entity_locality2_id_entity_id');
        $this->removeIndex('entity', 'entity_locality_type_id', array(
             'fields' => 
             array(
              0 => 'locality_type_id',
             ),
             ));
        $this->removeIndex('entity', 'entity_locality_id', array(
             'fields' => 
             array(
              0 => 'locality_id',
             ),
             ));
        $this->removeIndex('entity', 'entity_locality2_id', array(
             'fields' => 
             array(
              0 => 'locality2_id',
             ),
             ));
    }
}