<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{

  public function up()
  {
    $this->dropForeignKey('observation', 'observation_observer_id_observer_id');
    $this->dropForeignKey('observation', 'observation_entity_id_entity_id');
    $this->createForeignKey('observation', 'observation_observer_id_observer_id', array(
        'name' => 'observation_observer_id_observer_id',
        'local' => 'observer_id',
        'foreign' => 'id',
        'foreignTable' => 'observer',
        'onUpdate' => '',
        'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('observation', 'observation_entity_id_entity_id', array(
        'name' => 'observation_entity_id_entity_id_1',
        'local' => 'entity_id',
        'foreign' => 'id',
        'foreignTable' => 'entity',
        'onUpdate' => '',
        'onDelete' => 'CASCADE',
    ));
  }

  public function down()
  {
    $this->dropForeignKey('observation', 'observation_observer_id_observer_id');
    $this->dropForeignKey('observation', 'observation_entity_id_entity_id');

    $this->createForeignKey('observation', 'observation_observer_id_observer_id', array(
        'name' => 'observation_observer_id_observer_id',
        'local' => 'observer_id',
        'foreign' => 'id',
        'foreignTable' => 'observer',
    ));
    $this->createForeignKey('observation', 'observation_entity_id_entity_id', array(
        'name' => 'observation_entity_id_entity_id',
        'local' => 'entity_id',
        'foreign' => 'id',
        'foreignTable' => 'entity',
    ));
  }

}