<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('entity_type_translation', 'entity_type_translation_id_entity_type_id', array(
             'name' => 'entity_type_translation_id_entity_type_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'entity_type',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('entity_type_translation', 'entity_type_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('entity_type_translation', 'entity_type_translation_id_entity_type_id');
        $this->removeIndex('entity_type_translation', 'entity_type_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}