<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('device', 'data_source_id');
    }

    public function down()
    {
        $this->addColumn('device', 'data_source_id', 'integer', '8', array(
             ));
    }
}