<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('activation', 'activation_entity_id_entity_id', array(
             'name' => 'activation_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('activation', 'activation_data_source_id_entity_id', array(
             'name' => 'activation_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('activity', 'activity_entity_id_entity_id', array(
             'name' => 'activity_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('activity', 'activity_data_source_id_entity_id', array(
             'name' => 'activity_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('battery', 'battery_entity_id_entity_id', array(
             'name' => 'battery_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('battery', 'battery_data_source_id_entity_id', array(
             'name' => 'battery_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('entity', 'entity_locality_type_id_locality_type_id', array(
             'name' => 'entity_locality_type_id_locality_type_id',
             'local' => 'locality_type_id',
             'foreign' => 'id',
             'foreignTable' => 'locality_type',
             ));
        $this->createForeignKey('entity', 'entity_locality_id_entity_id', array(
             'name' => 'entity_locality_id_entity_id',
             'local' => 'locality_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('entity', 'entity_locality2_id_entity_id', array(
             'name' => 'entity_locality2_id_entity_id',
             'local' => 'locality2_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('entity', 'entity_type_entity_type_classname', array(
             'name' => 'entity_type_entity_type_classname',
             'local' => 'type',
             'foreign' => 'classname',
             'foreignTable' => 'entity_type',
             ));
        $this->createForeignKey('calendar', 'calendar_entity_id_entity_id', array(
             'name' => 'calendar_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('calendar', 'calendar_data_source_id_entity_id', array(
             'name' => 'calendar_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('data_source_affected', 'data_source_affected_data_source_id_entity_id', array(
             'name' => 'data_source_affected_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('data_source_affected', 'data_source_affected_entity_id_entity_id', array(
             'name' => 'data_source_affected_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('e_k_g', 'e_k_g_entity_id_entity_id', array(
             'name' => 'e_k_g_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('e_k_g', 'e_k_g_data_source_id_entity_id', array(
             'name' => 'e_k_g_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('force_cell', 'force_cell_entity_id_entity_id', array(
             'name' => 'force_cell_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('force_cell', 'force_cell_data_source_id_entity_id', array(
             'name' => 'force_cell_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('humidity', 'humidity_entity_id_entity_id', array(
             'name' => 'humidity_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('humidity', 'humidity_data_source_id_entity_id', array(
             'name' => 'humidity_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('light', 'light_entity_id_entity_id', array(
             'name' => 'light_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('light', 'light_data_source_id_entity_id', array(
             'name' => 'light_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('measurement', 'measurement_entity_id_entity_id', array(
             'name' => 'measurement_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('measurement', 'measurement_data_source_id_entity_id', array(
             'name' => 'measurement_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('motion', 'motion_entity_id_entity_id', array(
             'name' => 'motion_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('motion', 'motion_data_source_id_entity_id', array(
             'name' => 'motion_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('observation', 'observation_observer_id_observer_id', array(
             'name' => 'observation_observer_id_observer_id',
             'local' => 'observer_id',
             'foreign' => 'id',
             'foreignTable' => 'observer',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('observation', 'observation_entity_id_entity_id', array(
             'name' => 'observation_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('on_off', 'on_off_entity_id_entity_id', array(
             'name' => 'on_off_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('on_off', 'on_off_data_source_id_entity_id', array(
             'name' => 'on_off_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('open_closed', 'open_closed_entity_id_entity_id', array(
             'name' => 'open_closed_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('open_closed', 'open_closed_data_source_id_entity_id', array(
             'name' => 'open_closed_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('power', 'power_entity_id_entity_id', array(
             'name' => 'power_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('power', 'power_data_source_id_entity_id', array(
             'name' => 'power_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('sensor', 'sensor_device_id_device_id', array(
             'name' => 'sensor_device_id_device_id',
             'local' => 'device_id',
             'foreign' => 'id',
             'foreignTable' => 'device',
             ));
        $this->createForeignKey('sensor', 'sensor_data_source_id_entity_id', array(
             'name' => 'sensor_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('temperature', 'temperature_entity_id_entity_id', array(
             'name' => 'temperature_entity_id_entity_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('temperature', 'temperature_data_source_id_entity_id', array(
             'name' => 'temperature_data_source_id_entity_id',
             'local' => 'data_source_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             ));
        $this->createForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_forgot_password_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_group_permission_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_group_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_remember_key_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user', 'sf_guard_user_patient_id_entity_id', array(
             'name' => 'sf_guard_user_patient_id_entity_id',
             'local' => 'patient_id',
             'foreign' => 'id',
             'foreignTable' => 'entity',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('sf_guard_user', 'sf_guard_user_observer_id_observer_id', array(
             'name' => 'sf_guard_user_observer_id_observer_id',
             'local' => 'observer_id',
             'foreign' => 'id',
             'foreignTable' => 'observer',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_group_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_user_group_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_permission_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_user_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('entity_type_translation', 'entity_type_translation_classname_entity_type_classname', array(
             'name' => 'entity_type_translation_classname_entity_type_classname',
             'local' => 'classname',
             'foreign' => 'classname',
             'foreignTable' => 'entity_type',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('activation', 'activation_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('activation', 'activation_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('activity', 'activity_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('activity', 'activity_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('battery', 'battery_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('battery', 'battery_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('entity', 'entity_locality_type_id', array(
             'fields' => 
             array(
              0 => 'locality_type_id',
             ),
             ));
        $this->addIndex('entity', 'entity_locality_id', array(
             'fields' => 
             array(
              0 => 'locality_id',
             ),
             ));
        $this->addIndex('entity', 'entity_locality2_id', array(
             'fields' => 
             array(
              0 => 'locality2_id',
             ),
             ));
        $this->addIndex('entity', 'entity_type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
        $this->addIndex('calendar', 'calendar_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('calendar', 'calendar_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('data_source_affected', 'data_source_affected_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('data_source_affected', 'data_source_affected_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('e_k_g', 'e_k_g_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('e_k_g', 'e_k_g_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('force_cell', 'force_cell_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('force_cell', 'force_cell_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('humidity', 'humidity_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('humidity', 'humidity_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('light', 'light_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('light', 'light_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('measurement', 'measurement_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('measurement', 'measurement_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('motion', 'motion_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('motion', 'motion_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('observation', 'observation_observer_id', array(
             'fields' => 
             array(
              0 => 'observer_id',
             ),
             ));
        $this->addIndex('observation', 'observation_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('on_off', 'on_off_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('on_off', 'on_off_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('open_closed', 'open_closed_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('open_closed', 'open_closed_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('power', 'power_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('power', 'power_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('sensor', 'sensor_device_id', array(
             'fields' => 
             array(
              0 => 'device_id',
             ),
             ));
        $this->addIndex('sensor', 'sensor_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('temperature', 'temperature_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->addIndex('temperature', 'temperature_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->addIndex('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_group_permission', 'sf_guard_group_permission_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->addIndex('sf_guard_group_permission', 'sf_guard_group_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->addIndex('sf_guard_remember_key', 'sf_guard_remember_key_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_user', 'sf_guard_user_patient_id', array(
             'fields' => 
             array(
              0 => 'patient_id',
             ),
             ));
        $this->addIndex('sf_guard_user', 'sf_guard_user_observer_id', array(
             'fields' => 
             array(
              0 => 'observer_id',
             ),
             ));
        $this->addIndex('sf_guard_user_group', 'sf_guard_user_group_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_user_group', 'sf_guard_user_group_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->addIndex('sf_guard_user_permission', 'sf_guard_user_permission_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_user_permission', 'sf_guard_user_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->addIndex('entity_type_translation', 'entity_type_translation_classname', array(
             'fields' => 
             array(
              0 => 'classname',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('activation', 'activation_entity_id_entity_id');
        $this->dropForeignKey('activation', 'activation_data_source_id_entity_id');
        $this->dropForeignKey('activity', 'activity_entity_id_entity_id');
        $this->dropForeignKey('activity', 'activity_data_source_id_entity_id');
        $this->dropForeignKey('battery', 'battery_entity_id_entity_id');
        $this->dropForeignKey('battery', 'battery_data_source_id_entity_id');
        $this->dropForeignKey('entity', 'entity_locality_type_id_locality_type_id');
        $this->dropForeignKey('entity', 'entity_locality_id_entity_id');
        $this->dropForeignKey('entity', 'entity_locality2_id_entity_id');
        $this->dropForeignKey('entity', 'entity_type_entity_type_classname');
        $this->dropForeignKey('calendar', 'calendar_entity_id_entity_id');
        $this->dropForeignKey('calendar', 'calendar_data_source_id_entity_id');
        $this->dropForeignKey('data_source_affected', 'data_source_affected_data_source_id_entity_id');
        $this->dropForeignKey('data_source_affected', 'data_source_affected_entity_id_entity_id');
        $this->dropForeignKey('e_k_g', 'e_k_g_entity_id_entity_id');
        $this->dropForeignKey('e_k_g', 'e_k_g_data_source_id_entity_id');
        $this->dropForeignKey('force_cell', 'force_cell_entity_id_entity_id');
        $this->dropForeignKey('force_cell', 'force_cell_data_source_id_entity_id');
        $this->dropForeignKey('humidity', 'humidity_entity_id_entity_id');
        $this->dropForeignKey('humidity', 'humidity_data_source_id_entity_id');
        $this->dropForeignKey('light', 'light_entity_id_entity_id');
        $this->dropForeignKey('light', 'light_data_source_id_entity_id');
        $this->dropForeignKey('measurement', 'measurement_entity_id_entity_id');
        $this->dropForeignKey('measurement', 'measurement_data_source_id_entity_id');
        $this->dropForeignKey('motion', 'motion_entity_id_entity_id');
        $this->dropForeignKey('motion', 'motion_data_source_id_entity_id');
        $this->dropForeignKey('observation', 'observation_observer_id_observer_id');
        $this->dropForeignKey('observation', 'observation_entity_id_entity_id');
        $this->dropForeignKey('on_off', 'on_off_entity_id_entity_id');
        $this->dropForeignKey('on_off', 'on_off_data_source_id_entity_id');
        $this->dropForeignKey('open_closed', 'open_closed_entity_id_entity_id');
        $this->dropForeignKey('open_closed', 'open_closed_data_source_id_entity_id');
        $this->dropForeignKey('power', 'power_entity_id_entity_id');
        $this->dropForeignKey('power', 'power_data_source_id_entity_id');
        $this->dropForeignKey('sensor', 'sensor_device_id_device_id');
        $this->dropForeignKey('sensor', 'sensor_data_source_id_entity_id');
        $this->dropForeignKey('temperature', 'temperature_entity_id_entity_id');
        $this->dropForeignKey('temperature', 'temperature_data_source_id_entity_id');
        $this->dropForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id');
        $this->dropForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user', 'sf_guard_user_patient_id_entity_id');
        $this->dropForeignKey('sf_guard_user', 'sf_guard_user_observer_id_observer_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id');
        $this->dropForeignKey('entity_type_translation', 'entity_type_translation_classname_entity_type_classname');
        $this->removeIndex('activation', 'activation_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('activation', 'activation_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('activity', 'activity_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('activity', 'activity_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('battery', 'battery_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('battery', 'battery_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('entity', 'entity_locality_type_id', array(
             'fields' => 
             array(
              0 => 'locality_type_id',
             ),
             ));
        $this->removeIndex('entity', 'entity_locality_id', array(
             'fields' => 
             array(
              0 => 'locality_id',
             ),
             ));
        $this->removeIndex('entity', 'entity_locality2_id', array(
             'fields' => 
             array(
              0 => 'locality2_id',
             ),
             ));
        $this->removeIndex('entity', 'entity_type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
        $this->removeIndex('calendar', 'calendar_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('calendar', 'calendar_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('data_source_affected', 'data_source_affected_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('data_source_affected', 'data_source_affected_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('e_k_g', 'e_k_g_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('e_k_g', 'e_k_g_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('force_cell', 'force_cell_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('force_cell', 'force_cell_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('humidity', 'humidity_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('humidity', 'humidity_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('light', 'light_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('light', 'light_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('measurement', 'measurement_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('measurement', 'measurement_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('motion', 'motion_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('motion', 'motion_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('observation', 'observation_observer_id', array(
             'fields' => 
             array(
              0 => 'observer_id',
             ),
             ));
        $this->removeIndex('observation', 'observation_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('on_off', 'on_off_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('on_off', 'on_off_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('open_closed', 'open_closed_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('open_closed', 'open_closed_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('power', 'power_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('power', 'power_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('sensor', 'sensor_device_id', array(
             'fields' => 
             array(
              0 => 'device_id',
             ),
             ));
        $this->removeIndex('sensor', 'sensor_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('temperature', 'temperature_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->removeIndex('temperature', 'temperature_data_source_id', array(
             'fields' => 
             array(
              0 => 'data_source_id',
             ),
             ));
        $this->removeIndex('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_group_permission', 'sf_guard_group_permission_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->removeIndex('sf_guard_group_permission', 'sf_guard_group_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->removeIndex('sf_guard_remember_key', 'sf_guard_remember_key_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_user', 'sf_guard_user_patient_id', array(
             'fields' => 
             array(
              0 => 'patient_id',
             ),
             ));
        $this->removeIndex('sf_guard_user', 'sf_guard_user_observer_id', array(
             'fields' => 
             array(
              0 => 'observer_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_group', 'sf_guard_user_group_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_group', 'sf_guard_user_group_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_permission', 'sf_guard_user_permission_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_permission', 'sf_guard_user_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->removeIndex('entity_type_translation', 'entity_type_translation_classname', array(
             'fields' => 
             array(
              0 => 'classname',
             ),
             ));
    }
}