<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('temperature', 'value', 'float', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('temperature', 'value');
    }
}