<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('battery', 'level', 'enum', '', array(
             'values' => 
             array(
              0 => 'low',
              1 => 'normal',
             ),
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('battery', 'level');
    }
}