<?php

/**
 * PluginElectricStoveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginElectricStoveTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginElectricStoveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginElectricStove');
    }
}