<?php

/**
 * PluginFridgeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFridgeTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFridgeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFridge');
    }
}