<?php

/**
 * PluginCupboardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCupboardTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCupboardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCupboard');
    }
}