<?php

/**
 * PluginWardrobeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWardrobeTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWardrobeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWardrobe');
    }
}