<?php

/**
 * PluginBedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBedTable extends EntityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBed');
    }
}