<?php

/**
 * BaseEKG
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $started_by
 * @property integer $heart_rate
 * @property float $st_segment_elevation_ch1
 * @property float $st_segment_elevation_ch2
 * @property array $commonparams
 * @property array $channelparams
 * @property array $averages
 * 
 * @method string  getStartedBy()                Returns the current record's "started_by" value
 * @method integer getHeartRate()                Returns the current record's "heart_rate" value
 * @method float   getStSegmentElevationCh1()    Returns the current record's "st_segment_elevation_ch1" value
 * @method float   getStSegmentElevationCh2()    Returns the current record's "st_segment_elevation_ch2" value
 * @method array   getCommonparams()             Returns the current record's "commonparams" value
 * @method array   getChannelparams()            Returns the current record's "channelparams" value
 * @method array   getAverages()                 Returns the current record's "averages" value
 * @method EKG     setStartedBy()                Sets the current record's "started_by" value
 * @method EKG     setHeartRate()                Sets the current record's "heart_rate" value
 * @method EKG     setStSegmentElevationCh1()    Sets the current record's "st_segment_elevation_ch1" value
 * @method EKG     setStSegmentElevationCh2()    Sets the current record's "st_segment_elevation_ch2" value
 * @method EKG     setCommonparams()             Sets the current record's "commonparams" value
 * @method EKG     setChannelparams()            Sets the current record's "channelparams" value
 * @method EKG     setAverages()                 Sets the current record's "averages" value
 * 
 * @package    cce
 * @subpackage model
 * @author     Adam Banko (Cassus)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEKG extends TimedMeasurement
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('e_k_g');
        $this->hasColumn('started_by', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('heart_rate', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('st_segment_elevation_ch1', 'float', 10, array(
             'type' => 'float',
             'notnull' => true,
             'comment' => 'in volts',
             'length' => 10,
             'scale' => '6',
             ));
        $this->hasColumn('st_segment_elevation_ch2', 'float', 10, array(
             'type' => 'float',
             'notnull' => true,
             'comment' => 'in volts',
             'length' => 10,
             'scale' => '6',
             ));
        $this->hasColumn('commonparams', 'array', null, array(
             'type' => 'array',
             'notnull' => true,
             ));
        $this->hasColumn('channelparams', 'array', null, array(
             'type' => 'array',
             'notnull' => true,
             ));
        $this->hasColumn('averages', 'array', null, array(
             'type' => 'array',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}