<?php

/**
 * Activity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cce
 * @subpackage model
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Activity extends PluginActivity{
    protected function loadData($data){
        //sfContext :: getInstance() -> getLogger() -> info("[*] ".var_dump($data));
        
        $q = Doctrine_Query::create()
        -> select('a.id')
        -> from('ActivityType a')
        -> where('a.type = ?', $data['type']);
        $activity = $q -> execute();
        
        if(count($activity)){
            $this -> activity_type_id = $activity[0] -> getId();
            $this -> start_time = $data['start_time'];
            $this -> end_time = $data['end_time'];
        }else{
            throw new sfError404Exception("Unknown activity type: '{$data['type']}'");
        }
    }

}
