<?php

/**
 * CalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarTable extends PluginCalendarTable
{

  public static function getEvents($entity, $period)
  {
    $calendar = self::getInstance()->createQuery('m')
            ->select('m.ical')
            ->andWhere('m.entity_id = ?', $entity->id)
            ->limit(1)
            ->fetchOne(); /* @var $calendar Calendar */

    $parser = new qCal_Parser();
    $iCal = $parser->parse($calendar->ical);
    $events = array();
    foreach ($iCal->getComponent('VEVENT') as $event) /* @var $event qCal_Component_Vevent */
    {
      if ($event->hasProperty('RRULE'))
      {//@todo test and fix this later!
        /*$recurrenceSpec = $event->getRecurrence();
        echo "{$event->render()}";
        var_dump($recurrenceSpec);
        echo "\n\n";
        $recurrences = $recurrenceSpec->getRecurrences("20110520T180000Z", "20110528T180000Z");

        foreach ($recurrences as $recurrence)
        {
          $events[] = $tmp = $event->getAtRecurrence($recurrence);
        }*/
      }
      else
      {
        //@todo filter to the time interval!
        $events[] = $event;
      }
    }
    return $events;
  }

  /**
   * Returns an instance of this class.
   *
   * @return object CalendarTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Calendar');
  }

}