<?php

/**
 * BedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BedTable extends PluginBedTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object BedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bed');
    }
}