<?php

/**
 * CupboardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CupboardTable extends PluginCupboardTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CupboardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cupboard');
    }
}