<?php

/**
 * ElectricStoveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElectricStoveTable extends PluginElectricStoveTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElectricStoveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElectricStove');
    }
}